#!/usr/bin/env bash
modules="cli;ip;linux"
for name in ${modules//;/ }
do
    echo "Formatting $name"
    clang-format -i include/tds/$fmtdir/*.hpp
    clang-format -i src/$fmtdir/*.cpp
    clang-format -i tests/unit/$fmtdir/*.cpp
done
