#!/usr/bin/env bash
modules="cli;cli/user_commands;config;ip;linux;protocol;server;user"
for name in ${modules//;/ }
do
    echo "Formatting $name"
    clang-format -i include/tds/$name/*.hpp
    clang-format -i src/$name/*.cpp
    clang-format -i tests/unit/$name/*.cpp
done

clang-format -i src/main.cpp
