include(GNUInstallDirs)
set_target_properties(tds PROPERTIES INSTALL_RPATH "${CMAKE_INSTALL_FULL_LIBDIR}")

install(
    TARGETS tds-dev tds
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
)

set(CPACK_PACKAGE_NAME "TinDoxServer")
set(CPACK_PACKAGE_FILE_NAME ${CPACK_PACKAGE_NAME})

set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH})

set(CPACK_PACKAGE_VENDOR "Jakub Mazurkiewicz")
set(CPACK_PACKAGE_CONTACT "${CPACK_PACKAGE_VENDOR} <mazkuba3@gmail.com>")
set(CPACK_GENERATOR DEB)

include(CPack)

