SET(CMAKE_INSTALL_RPATH ${CMAKE_INSTALL_LIBDIR})

include(GNUInstallDirs)

install(
    TARGETS tds-dev
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
)

install(
    TARGETS tds
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
)
