include(GNUInstallDirs)
set_target_properties(tds PROPERTIES INSTALL_RPATH "${CMAKE_INSTALL_FULL_LIBDIR}")

install(
    TARGETS tds-dev tds
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
)
