name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  project:
    name: Build TIN project
    runs-on: ubuntu-latest

    steps:
    - name: Init
      run: echo Init
