name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  project:
    name: Build TIN project
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest]
        c_compiler: [gcc-11]
        cxx_compiler: [g++-11]
        build_type: [Debug, Release]

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - name: Install compilers
      run: sudo apt install ${{matrix.c_compiler}} ${{matrix.cxx_compiler}}

    - name: Configure CMake
      env:
        CC: ${{matrix.c_compiler}}
        CXX: ${{matrix.cxx_compiler}}
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build project
      run: cmake --build build --config ${{matrix.build_type}}

    - name: Run tests
      run: |
        cd build
        ctest -C ${{matrix.build_type}}
