name: "Documentation"

on:
  push:
    branches: [main]
    paths: ['docs-pl/*.tex']
  pull_request:
    branches: [main]
    paths: ['docs-pl/*.tex']

jobs:
  docs:
    name: Build LaTeX documentation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build documentation
      uses: xu-cheng/latex-action@v2
      with:
        root_file: docs-pl/*.tex
        glob_root_file: true
