name: Test documentation

on:
  push:
    paths: ['docs-pl/src/**']
  pull_request:
    paths: ['docs-pl/src/**']

jobs:
  docs:
    name: Build LaTeX documentation
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-20.04]
        doctype: [preliminary]

    steps:
    - uses: actions/checkout@v2

    - uses: dante-ev/latex-action@latest
      with:
        root_file: '${{doctype}}-documentation.tex'
        working_directory: 'docs-pl/src/${{doctype}}-documentation'
