name: Documentation

on:
  push:
    branches: [main]
    paths: ['docs-pl/src/*.tex']
  pull_request:
    branches: [main]
    paths: ['docs-pl/src/*.tex']

jobs:
  docs:
    name: Build LaTeX documentation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

      uses: xu-cheng/latex-action@v2
      with:
        root_file: docs-pl/src/*.tex
        glob_root_file: true
