name: Create release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  server:
    name: Create TDS release
    runs-on: ubuntu-20.04

    defaults:
      run:
        shell: bash
        working-directory: server

    steps:
    - uses: actions/checkout@v2

    - name: Build project
      env:
        CC: gcc-11
        CXX: g++-11
      run: |
        sudo apt install $CC $CXX
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cd build
        cmake --build .
        sudo cpack
        shasum -a 256 TinDoxServer.deb > TinDoxServer.deb.sha256

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          server/build/TinDoxServer.deb*
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
